omd-nagios:
    container_name: omd-nagios
    image: local/omd-labs-centos-sakuli:github-204-docker-cloud
    # TODO TS use new image!
    # OMD with runtime data backup
#    image: toschneck/omd-nagios-demo:01-2017
    ports:
    - 8043:443
    cpu_quota: 65000
    environment:
    - TZ=Europe/Berlin
    volumes:
    - /etc/localtime:/etc/localtime
    - ./omd_ansible_drop-in_role/:/root/ansible_dropin
