omd-nagios:
    container_name: omd-nagios
#    image: consol/sakuli-omd-labs-ubuntu
    # TODO TS use new image!
    # OMD with runtime data backup
    image: toschneck/omd-nagios-demo:container-conf
    ports:
    - 8043:443
    cpu_quota: 65000
    environment:
    - TZ=Europe/Berlin
    volumes:
    - /etc/localtime:/etc/localtime
    - ./omd_ansible_drop-in_role/:/root/ansible/dropin_role
