omd-nagios:
    container_name: omd-nagios
    image: consol/sakuli-omd-labs-ubuntu
    ports:
    - 8043:443
    cpu_quota: 65000
    volumes:
    - /etc/localtime:/etc/localtime                                                                                               v
    - ./omd_ansible_drop-in_role/:/root/ansible/dropin_role
