omd-nagios:
    container_name: omd-nagios
    image: consol/omd-labs-ubuntu-sakuli
    ports:
    - 8043:80
    cpu_quota: 65000
    volumes:
    - /etc/localtime:/etc/localtime
    - ./config/sakuli_nagios_objects.cfg:/opt/omd/sites/demo/etc/nagios/conf.d/sakuli_nagios_objects.cfg
