#docker-compose file for the second server environment

activemq-broker2:
  container_name: activemq-broker2
  image: consol/activemq-5.12

bakery-web-server2:
  container_name: bakery-web-server2
  image: consol/bakery-web-app
#  ports:
#  - 18001:8080
  links:
  - activemq-broker2:activemq
  - bakery-worker-chocolate2
  - bakery-worker-blueberry2
  - bakery-worker-caramel2
  environment:
  - ACTIVEMQ_PORT_61616_TCP_ADDR=activemq
  - ACTIVEMQ_PORT_61616_TCP_PORT=61616

bakery-report-server2:
  container_name: bakery-report-server2
  image: consol/bakery-report
#  ports:
#  - 18002:8080

bakery-worker-chocolate2:
  container_name: bakery-worker-chocolate2
  image: consol/bakery-worker
  links:
  - bakery-report-server2:report
  - activemq-broker2:activemq
  environment:
  - FACTORY_TYPE=chocolate
  - FACTORY_COSTS=200
  - ACTIVEMQ_PORT_61616_TCP_ADDR=activemq
  - ACTIVEMQ_PORT_61616_TCP_PORT=61616

bakery-worker-blueberry2:
  container_name: bakery-worker-blueberry2
  image: consol/bakery-worker
  links:
  - bakery-report-server2:report
  - activemq-broker2:activemq
  environment:
  - FACTORY_TYPE=blueberry
  - FACTORY_COSTS=400
  - ACTIVEMQ_PORT_61616_TCP_ADDR=activemq
  - ACTIVEMQ_PORT_61616_TCP_PORT=61616

bakery-worker-caramel2:
  container_name: bakery-worker-caramel2
  image: consol/bakery-worker
  links:
  - bakery-report-server2:report
  - activemq-broker2:activemq
  environment:
  - FACTORY_TYPE=caramel
  - FACTORY_COSTS=500
  - ACTIVEMQ_PORT_61616_TCP_ADDR=activemq
  - ACTIVEMQ_PORT_61616_TCP_PORT=61616