jenkinsmaster:
  build: .
  ports:
    - 8080:8080
  cpu_quota: 65000
  volumes:
    # mount the jenkins_configuraton folder
    - ./jenkins_conf:/var/jenkins_home
    # mount the host system time to the container
    - /etc/localtime:/etc/localtime:ro
    # mount Docker daemon to master
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
  # set correct timezone
  - TZ=Europe/Berlin

#volumes:
#  jenkins_conf:
#    driver: local
